version: '3'

services:
  linux:
    build: .
    restart: always
    command: sleep 1000
    cap_add:
      - SYS_PTRACE
    volumes:
      - .:/cronitor

  alpine:
    image: alpine:latest
    restart: no
    command: tail -f /dev/null
    cap_add:
      - SYS_PTRACE
    volumes:
      - .:/cronitor
